; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = v2-sensor

[env]
platform = espressif32
framework = arduino, espidf
monitor_speed = 115200
monitor_filters = direct
board_build.filesytem = littlefs
build_unflags = -std=gnu++2b -std=gnu++11
build_flags = -std=gnu++2a
lib_deps = 
    adafruit/Adafruit BusIO@^1.17.2
    adafruit/Adafruit ADS1X15@^2.5.0
    jgromes/RadioLib@^7.6.0

[env:nanoatmega328]
build_src_filter = +<*> -<port/> +<port/arduino>
platform = atmelavr
board = nanoatmega328new
board_build.mcu = atmega328p
framework = arduino
lib_deps =
    ${env.lib_deps}
    feilipu/FreeRTOS@^11.1.0-3
build_unflags = -std=gnu++2a
build_flags = 
    ${env.build_flags}
    -D LORA_RADIO=SX1276
    -D LORA_BUSY=GPIO_NUM_NC
    -D LORA_CS=GPIO_NUM_8
    -D LORA_SCK=GPIO_NUM_9
    -D LORA_DIO0=GPIO_NUM_14
    -D LORA_MISO=GPIO_NUM_11
    -D LORA_MOSI=GPIO_NUM_10
    -D LORA_RST=GPIO_NUM_12

[env:v3-sensor]
build_src_filter = +<*> -<port/> +<port/esp32>
board = heltec_wifi_lora_32_V3
build_flags = 
    ${env.build_flags}
    -D ADS1115_SDA=GPIO_NUM_NC
    -D ADS1115_SCL=GPIO_NUM_NC
    -D PRG_BUTTON=GPIO_NUM_0
    -D STATUS_LED=GPIO_NUM_35
    -D LORA_RADIO=SX1262
    -D LORA_BUSY=GPIO_NUM_13
    -D LORA_CS=GPIO_NUM_8
    -D LORA_SCK=GPIO_NUM_9
    -D LORA_DIO0=GPIO_NUM_14
    -D LORA_MISO=GPIO_NUM_11
    -D LORA_MOSI=GPIO_NUM_10
    -D LORA_RST=GPIO_NUM_12
    -D IS_SENSOR_NODE

[env:v2-sensor]
build_src_filter = +<*> -<port/> +<port/esp32>
board = heltec_wifi_lora_32_V2
build_flags = 
    ${env.build_flags}
    -D ADS1115_SDA=GPIO_NUM_13
    -D ADS1115_SCL=GPIO_NUM_21
    -D PRG_BUTTON=GPIO_NUM_0
    -D STATUS_LED=GPIO_NUM_25
    -D LORA_RADIO=SX1276
    -D LORA_BUSY=GPIO_NUM_NC
    -D LORA_CS=GPIO_NUM_18
    -D LORA_SCK=GPIO_NUM_5
    -D LORA_DIO0=GPIO_NUM_26
    -D LORA_MISO=GPIO_NUM_19
    -D LORA_MOSI=GPIO_NUM_27
    -D LORA_RST=GPIO_NUM_14
    -D IS_SENSOR_NODE

[env:v2-gateway]
board_build.filesytem = littlefs
board_build.partitions = partitions_8MB.csv
lib_deps =
    ${env.lib_deps}
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
build_flags =
    ${env.build_flags}
    -Os
    -D DISABLE_RTDB
    -D DISABLE_ERROR_QUEUE
    -D DISABLE_FCM
    -D DISABLE_FB_STORAGE
    -D DISABLE_GC_STORAGE
    -D DISABLE_PSRAM
    -D DISABLE_ERROR_STRING
    -D DISABLE_OTA
    -D DISABLE_SD
    -D DISABLE_FLASH
    -D DISABLE_DEBUG
    -D ENABLE_FB_FUNCTIONS
    -D ENABLE_FIRESTORE
