; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = v2-sensor

[env]
platform = espressif32
framework = arduino, espidf
monitor_speed = 115200
monitor_filters = direct
board_build.filesytem = littlefs
build_unflags = -std=gnu++11
build_flags =
    -D RADIOLIB_EXCLUDE_SX128X=1
    -D RADIOLIB_EXCLUDE_SX127X=1
    -D RADIOLIB_EXCLUDE_SX126X=1
    -D RADIOLIB_EXCLUDE_SX1231=1
    -D RADIOLIB_EXCLUDE_SI433X=1
    -D RADIOLIB_EXCLUDE_RFM2X=1
    -D RADIOLIB_EXCLUDE_RF69=1
    -D RADIOLIB_EXCLUDE_NRF24=1
    -D RADIOLIB_EXCLUDE_LR2021=1
    -D RADIOLIB_EXCLUDE_LR11X0=1
    -D RADIOLIB_EXCLUDE_LLCC68=1
    -D RADIOLIB_EXCLUDE_CC1101=1
    -D RADIOLIB_EXCLUDE_ADSB=1
    -D RADIOLIB_EXCLUDE_AFSK=1
    -D RADIOLIB_EXCLUDE_APRS=1
    -D RADIOLIB_EXCLUDE_AX25=1
    -D RADIOLIB_EXCLUDE_BELL=1
    -D RADIOLIB_EXCLUDE_FSK4=1
    -D RADIOLIB_EXCLUDE_HELLSCHREIBER=1
    -D RADIOLIB_EXCLUDE_LORAWAN=1
    -D RADIOLIB_EXCLUDE_MORSE=1
    -D RADIOLIB_EXCLUDE_PAGER=1
    -D RADIOLIB_EXCLUDE_RTTY=1
    -D RADIOLIB_EXCLUDE_SSTV=1
    -D RADIOLIB_EXCLUDE_DIRECT_RECEIVE=1
lib_deps = 
    adafruit/Adafruit BusIO@^1.17.2
    adafruit/Adafruit ADS1X15@^2.5.0
    jgromes/RadioLib@^7.6.0

[env:nanoatmega328]
build_src_filter = +<*> -<lora/> -<port/esp32> +<port/arduino>
platform = atmelavr
board = nanoatmega328new
board_build.mcu = atmega328p
framework = arduino
lib_deps =
    sandeepmistry/LoRa@^0.8.0
    feilipu/FreeRTOS@^11.1.0-3
    embeddedartistry/LibPrintf@^1.2.13
build_unflags =
    -D RADIOLIB_EXCLUDE_SX127X=1
build_flags = 
    ${env.build_flags}
    -Os
    -D LORA_RADIO=SX1276
    -D LORA_BUSY=RADIOLIB_NC
    -D LORA_CS=SS
    -D LORA_SCK=SCK
    -D LORA_DIO0=2
    -D LORA_MISO=MISO
    -D LORA_MOSI=MOSI
    -D LORA_RST=3

[env:v3-sensor]
board = heltec_wifi_lora_32_V3
build_unflags =
    -D RADIOLIB_EXCLUDE_SX126X=1
build_flags = 
    ${env.build_flags}
    -D ADS1115_SDA=GPIO_NUM_NC
    -D ADS1115_SCL=GPIO_NUM_NC
    -D PRG_BUTTON=GPIO_NUM_0
    -D STATUS_LED=GPIO_NUM_35
    -D LORA_RADIO=SX1262
    -D LORA_BUSY=GPIO_NUM_13
    -D LORA_CS=GPIO_NUM_8
    -D LORA_SCK=GPIO_NUM_9
    -D LORA_DIO0=GPIO_NUM_14
    -D LORA_MISO=GPIO_NUM_11
    -D LORA_MOSI=GPIO_NUM_10
    -D LORA_RST=GPIO_NUM_12
    -D IS_SENSOR_NODE

[env:v2-sensor]
board = heltec_wifi_lora_32_V2
build_unflags =
    -D RADIOLIB_EXCLUDE_SX127X=1
build_flags = 
    ${env.build_flags}
    -D ADS1115_SDA=GPIO_NUM_13
    -D ADS1115_SCL=GPIO_NUM_21
    -D PRG_BUTTON=GPIO_NUM_0
    -D STATUS_LED=GPIO_NUM_25
    -D LORA_RADIO=SX1276
    -D LORA_BUSY=GPIO_NUM_NC
    -D LORA_CS=GPIO_NUM_18
    -D LORA_SCK=GPIO_NUM_5
    -D LORA_DIO0=GPIO_NUM_26
    -D LORA_MISO=GPIO_NUM_19
    -D LORA_MOSI=GPIO_NUM_27
    -D LORA_RST=GPIO_NUM_14
    -D IS_SENSOR_NODE

[env:v2-gateway]
board = heltec_wifi_lora_32_V2
board_build.filesytem = littlefs
board_build.partitions = partitions_8MB.csv
build_unflags =
    -D RADIOLIB_EXCLUDE_SX127X=1
    -D IS_SENSOR_NODE
lib_deps =
    ${env.lib_deps}
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
build_flags =
    ${env:v2-sensor.build_flags}
    -Os
    -D DISABLE_RTDB
    -D DISABLE_ERROR_QUEUE
    -D DISABLE_FCM
    -D DISABLE_FB_STORAGE
    -D DISABLE_GC_STORAGE
    -D DISABLE_PSRAM
    -D DISABLE_ERROR_STRING
    -D DISABLE_OTA
    -D DISABLE_SD
    -D DISABLE_FLASH
    -D DISABLE_DEBUG
    -D ENABLE_FB_FUNCTIONS
    -D ENABLE_FIRESTORE
